NAME = Bureaucrat
SRCS = ${addsuffix .cpp, main Intern AForm ShrubberyCreationForm RobotomyRequestForm PresidentialPardonForm Bureaucrat}
INCL = ${addsuffix .hpp, Intern AForm ShrubberyCreationForm RobotomyRequestForm PresidentialPardonForm Bureaucrat}

include ../template.mk
