NAME = Bureaucrat
SRCS = ${addsuffix .cpp, main AForm ShrubberyCreationForm RobotomyRequestForm PresidentialPardonForm Bureaucrat}
INCL = ${addsuffix .hpp, AForm ShrubberyCreationForm RobotomyRequestForm PresidentialPardonForm Bureaucrat}

include ../template.mk
